### ISSUE TITLE
Repository doesn't really belong in this organization

### ISSUE THREAD

**Issue by tkw1536** [OpenJUB/usg-constitution#1]
This GitHub organization is really intended for code projects for Jacobs students and is inherently non-political (i.e. it is not part of the USG). 
I am not sure that the usg constitution belongs here, it should really go into a dedicated USG organization.

**Comment by ColinRothgang** [comment]
Personally, I believe this document should be maintained via a version control system on a platform like Github (to enforce a public change history) and that it will need to be maintained by the IT department based on changes decided on in the Parliament (probably the only feasible solution). 
I do however see the point that this organization (OpenJUB) is probably the wrong place to put it and that there should be an USG organization instead. 
I will talk to Abhik and set something up.

**Comment by abhikpal** [comment]
This repo has been moved to the Gitlab organization for the student government: https://gitlab.com/jub-usg/usg-minutes I'm closing this issue and archiving the repository.
